version: '2'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # image: golang:1.15.1-alpine
        volumes:
          - .:/go/src/BE-AalailsonAndrade/user-api
        working_dir: /go/src/BE-AalailsonAndrade/user-api
        # command: air -c .air.toml
        environment:
            REDIS_URL: redis_user:6379
    redis_user:
        image: sickp/alpine-redis:3.2.2
        # ports:
            # - "6379:6379"
        depends_on:
            - helper
    helper:
        image: alpine
        command: sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo 'vm.overcommit_memory=1' > /etc/sysctl.conf && sysctl vm.overcommit_memory=1" 
        privileged: true
